#!/usr/bin/env bash

set -e

for x in a b; do
   openssl req -batch -new -x509 -newkey rsa:2048 -nodes -sha256 \
    -subj /CN=$x.example.org/O=oreore -days 3650 \
    -keyout docker/nginx/$x.key \
    -out docker/nginx/$x.crt
done
