#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# My site is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e


cp -r /opt/invenio/var/instance /opt/invenio/var/instance2
cp /opt/invenio/var/instance/wekoA.cfg /opt/invenio/var/instance/invenio.cfg 
cp /opt/invenio/var/instance/wekoB.cfg /opt/invenio/var/instance2/invenio.cfg 

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create
pipenv run invenio index destroy --force --yes-i-know
pipenv run invenio index init --force
pipenv run invenio index queue init purge

# Create admin role to rectict access
pipenv run invenio roles create admin
pipenv run invenio access allow superuser-access role admin



